[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "pip install -r requirements_production.txt",
  "cd theme/static_src && npm install && npm run build"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
