[phases.install]
cmds = [
  "pip install -r requirements_production.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
